# docker-compose.yml (solo BD local para desarrollo)
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eklesa_subscriptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Puerto diferente para no chocar con otros servicios